apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: mini-admin
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: mini-admin-cluster
rules:
- apiGroups: ["", "networking.k8s.io", "storage.k8s.io", "rbac.authorization.k8s.io"]
  resources: [
    "pods", 
    "pods/log",
    "configmaps", 
    "secrets", 
    "services",
    "nodes",
    "networkpolicies",
    "serviceaccounts", 
    "persistentvolumeclaims",
    "daemonsets",
    "replicasets", 
    "statefulsets", 
    "cronjobs", 
    "storageclasses",
    "clusterroles", 
    "clusterrolebindings",
    "roles",
    "rolebindings"

  ]
  verbs: ["get", "watch", "list", "create", "delete"]






