apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailboxes
  namespace: migrate
spec:
  storageClassName: temp-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi