services:
  nginx:
    build:
      context: ./
    container_name: nginx
    volumes:
      - /var/www/sites_available/:/var/www/sites_available/
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/log/nginx:/var/log/nginx/

    restart: unless-stopped
    ports:
    - 9009:80
    - 8443:443
    - 7080:8080