version: '3'
services:
  bind9:
    container_name: ab-cloud_dns
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=Africa/Casablanca
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind-config/:/etc/bind
      - ./cache/:/var/cache/bind
      - ./records/:/var/lib/bind
    restart: unless-stopped
    networks:
      dns-network:
        ipv4_address: 172.20.0.10

networks:
  dns-network:
    external: true
