services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_master
    restart: always
    volumes:
    - jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    ports:
    - 3553:8080
    
    dns: 
    - 10.80.1.191

volumes:
  jenkins_data: